update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,7 +19,11 @@ jobs:
           name: Add EC2 Host to known_hosts
           command: |
             mkdir -p ~/.ssh
-            ssh-keyscan $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
+            echo "EC2_PUBLIC_DNS: $EC2_PUBLIC_DNS"
+            ssh-keyscan -H "$EC2_PUBLIC_DNS" >> ~/.ssh/known_hosts || {
+            echo "❌ ssh-keyscan failed. Check EC2_PUBLIC_DNS." >&2
+            exit 1
+           }
 
       - run:
           name: Package Spring Boot application (Java 8)
