update

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,10 +20,7 @@ jobs:
           command: |
             mkdir -p ~/.ssh
             echo "EC2_PUBLIC_DNS: $EC2_PUBLIC_DNS"
-            ssh-keyscan -H "$EC2_PUBLIC_DNS" >> ~/.ssh/known_hosts || {
-            echo "❌ ssh-keyscan failed. Check EC2_PUBLIC_DNS." >&2
-            exit 1
-           }
+            ssh-keyscan -H "$EC2_PUBLIC_DNS" >> ~/.ssh/known_hosts || { echo "❌ ssh-keyscan failed. Check EC2_PUBLIC_DNS." >&2; exit 1; }
 
       - run:
           name: Package Spring Boot application (Java 8)
